### ISSUE TITLE
Import circulaire et relatif ne fonctionne pas en Windows

### ISSUE THREAD

**Issue by agingrasc** [RoboCupULaval/RULEngine#11]
Relevé par @david2194 l'import de geometry.py concernant area ne fonctionne pas en Windows.
De façon plus général, le submodule dans StrategyIA ne semble pas à jour.

**Comment by agingrasc** [comment]
@felixpelletier: fix that shit permenently please

**Comment by agingrasc** [comment]
Devrait être réglé par l'issue #15

**Comment by MaitreMenard** [comment]
L'import circulaire est résolu par les changements du pull request #20
