### ISSUE TITLE
Unit test geometry.py

### ISSUE THREAD

**Issue by MaitreMenard** [RoboCupULaval/RULEngine#33]
Écrire les unit tests pour les fonctions dans geometry.py. Voir les tests de vector.py ou de StrategyIA/info_manager.py pour des exemples.

**Comment by AlexandraMercier** [comment]
Pull request crée, il y a une erreur à régler dont je ne suis pas sûre comment procéder
Dans test_get_nearest, le assertEqual s'attend à Position, mais reçoit [Position] quand c'est 1 élément.
Je ne sais pas si c'est voulu ou non, ou si on veut faire un cas spécial de retourner Position, si une seule position est demandée dans get_nearest.
