### ISSUE TITLE
Les robots ne s'arrêtent pas après l'interruption de l'IA

### ISSUE THREAD

**Issue by etibuteau** [RoboCupULaval/RULEngine#40]
Des commandes d'arrêts devraient être envoyés lorsque l'IA est arrêtée.

**Comment by agingrasc** [comment]
Non reproduit.
Le gui ne peut pas arrêter les robots si l'IA ne roule pas.
Ce serait une amélioration possible (le GUI peut parfaitement envoyer les commandes puisque c'est une communication UDP).
