### ISSUE TITLE
Ajouter un asservissement PI

### ISSUE THREAD

**Issue by agingrasc** [RoboCupULaval/RULEngine#43]
**Expérimental**

Ajouter un asservissement _proportionnel_ _intégré_ en position.
## Architecture

Ajouter une classe PI qui est instancié lors du traitement d'une nouvelle commande.
Une instance de cette classe est maintenu pour chaque robot.
La classe expose une méthode de mise à jour qui prend comme paramètre une position (consigne).
Cette méthode retourne la consigne en vitesse à appliquer au robot.
- [x] Créer la classe avec l’échafaudage nécessaire pour calculer les valeurs PI
- [x] Implémenter la mise à jour
- [x] Expérimentalement trouver des valeurs de gains statique et de gain intégral avec le simulateur
- [ ] Expérimentalement raffiner les valeurs des gains avec des tests d'intégrations.
- [ ] Unit test des nouvelles fonctionnalités

**Comment by MaitreMenard** [comment]
L'asservissement force les orientations de chaque commande à environ 0. Les robots ne tournent donc pas lorsqu'on roule les stratégies dans StrategyIA. Si c'est voulu en raison de considérations avec l'embarqué, il serait bien de trouver une façon que ça n'affecte pas les tests des stratégies.
